Updated Readme with DB schema
CSCI-GA-2820-SP23-003/inventory pull request #51
Opened 2023-03-31 18:28 UTC by nishanthsanjeev

Added DB schema

2023-04-01 00:23 UTC, sahildeshpande25 requested changes

2023-04-01 00:23 UTC, sahildeshpande25 commented on README.md
> +| created_at   | Date        | Date of creation of item            | No            |
```suggestion
| created_at   | DateTime        | Time of creation of item            | No            |
```

2023-04-01 00:23 UTC, sahildeshpande25 commented on README.md
> +| updation_at   | Date        | Date of updation of item            | No            |
```suggestion
| updated_at   | DateTime        | Time of updation of item            | No            |
```

2023-04-01 00:37 UTC, sahildeshpande25 approved these changes

2023-04-02 15:35 UTC, shradhaiyer approved these changes

2023-04-02 15:35 UTC, merged