Delete UI
CSCI-GA-2820-SP23-003/inventory pull request #90
Opened 2023-04-14 16:39 UTC by zhengtr

- Add delete UI in `rest_api.js`
- import and use `flask.make_response` in `routes.py`
- No `abort` is called so the message string should work fine

2023-04-14 22:00 UTC, nishanthsanjeev requested changes
Your changes are good - can you also add support for a 'Success' message to be displayed when we delete an Inventory item? In the given screenshot, note how there is a success message displayed when an item is created.

<img width="1440" alt="Screenshot 2023-04-14 at 5 59 04 PM" src="https://user-images.githubusercontent.com/46843952/232162022-4c906038-8064-4fae-99d3-bc76a72ed7af.png">

2023-04-14 22:26 UTC, sahildeshpande25 commented
@zhengtr can you merge master into your branch? My PR was just merged so you'll have to pull from master first.

2023-04-14 22:26 UTC, sahildeshpande25 commented
> Your changes are good - can you also add support for a 'Success' message to be displayed when we delete an Inventory item? In the given screenshot, note how there is a success message displayed when an item is created.
> 
There are flash messages supported on lines 100 and 104 but the delete function is outside the main function and can't access the flash message function as it is out of scope. You will have to move your function inside the main function.

2023-04-15 05:00 UTC, zhengtr commented
> Your changes are good - can you also add support for a 'Success' message to be displayed when we delete an Inventory item? In the given screenshot, note how there is a success message displayed when an item is created.
> 
> <img alt="Screenshot 2023-04-14 at 5 59 04 PM" width="1440" src="https://user-images.githubusercontent.com/46843952/232162022-4c906038-8064-4fae-99d3-bc76a72ed7af.png">

I was trying to add it as well but couldn't figure out how. Would you please let me know how to do that?

2023-04-15 15:39 UTC, sahildeshpande25 commented on service/static/js/rest_api.js
> +    });
```suggestion

    // ****************************************
    // Delete a Pet
    // ****************************************

    $("#delete-btn").click(function () {

        let inventory_id = $("#inventory_id").val();

        $("#flash_message").empty();

        let ajax = $.ajax({
            type: "DELETE",
            url: `/inventory/${inventory_id}`,
            contentType: "application/json",
            data: '',
        })

        ajax.done(function(res){
            clear_form_data()
            flash_message("Item has been Deleted!")
        });

        ajax.fail(function(res){
            flash_message("Server error!")
        });
    });
}}
```

2023-04-15 15:40 UTC, sahildeshpande25 commented on service/static/js/rest_api.js
> +    });
@zhengtr the suggested change should fix it

2023-04-15 16:34 UTC, zhengtr commented
> > Your changes are good - can you also add support for a 'Success' message to be displayed when we delete an Inventory item? In the given screenshot, note how there is a success message displayed when an item is created.
> 
> There are flash messages supported on lines 100 and 104 but the delete function is outside the main function and can't access the flash message function as it is out of scope. You will have to move your function inside the main function.

Hey @sahildeshpande25  I am sorry that I didn't see this comment by you (otherwise I would know how to fix it without you providing the code details). 

I have fixed it and also merged with master. Please review @sahildeshpande25 @nishanthsanjeev

2023-04-15 17:57 UTC, sahildeshpande25 commented
@zhengtr while merging master into your branch, you have deleted the restock function in `rest_api.js`

2023-04-15 19:26 UTC, zhengtr commented
> @zhengtr while merging master into your branch, you have deleted the restock function in `rest_api.js`

@sahildeshpande25 Some weird things happened when I applied suggested changes. It's fixed now.

2023-04-16 02:17 UTC, nishanthsanjeev approved these changes

2023-04-16 02:25 UTC, sahildeshpande25 approved these changes
Delete button works as expected.

2023-04-16 02:25 UTC, merged